### ISSUE TITLE
Unable to load asset:

### ISSUE THREAD

**Issue by alaabashiyi** [RatelHub/rflutter_alert#86]
first of all thanks for this awesome package !! works great but having this weird issue,
When alert pop ups it throws this error in the console.

it could be something related to my project version but i just wanted to tell you guys because im not quite sure what is it.

Thanks

════════ Exception caught by image resource service ══════
The following assertion was thrown resolving an image codec:
Unable to load asset: packages/rflutter_alert/assets/images/close.png

When the exception was thrown, this was the stack: 
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:225:7)
<asynchronous suspension>
#1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:668:31)
#2      AssetBundleImageProvider.load (package:flutter/src/painting/image_provider.dart:651:14)
#3      ImageProvider.resolveStreamForKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:504:13)
...
Image provider: AssetImage(bundle: null, name: "packages/rflutter_alert/assets/images/close.png")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#dd904(), name: "packages/rflutter_alert/assets/images/close.png", scale: 1.0)
═══════════════════════════════════════════════════════════

**Comment by alaabashiyi** [comment]
oh sorry i just noticed that my issue was duplicated !, closing this issue
